# Generated by Django 4.2.11 on 2024-06-14 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
