# Generated by Django 4.2.11 on 2024-06-19 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0002_alter_category_user_alter_type_name_alter_type_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Category1', 'Category 1'), ('Category2', 'Category 2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assistants.category'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('Full Time', 'full time'), ('Part Time', 'part time')], default='Chouse', max_length=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assistants.type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('Type1', 'Type 1'), ('Type2', 'Type 2')], max_length=50),
        ),
    ]
