# Generated by Django 4.2.11 on 2024-06-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0007_category_user_type_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='type',
            name='user',
        ),
    ]
