# Generated by Django 4.2.11 on 2024-06-19 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0010_category_user_offer_user_type_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assistants.category'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assistants.type'),
        ),
    ]
