# Generated by Django 5.0.4 on 2024-05-06 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assistantFinder", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="token",
            old_name="date",
            new_name="timestamp",
        ),
    ]
