# Generated by Django 5.0.4 on 2024-05-06 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistantFinder", "0002_rename_date_token_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="request",
            name="requestType",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="assistantFinder.type",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="requestType",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="assistantFinder.type",
            ),
        ),
    ]
