# Generated by Django 5.0.1 on 2024-04-30 10:10

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "assistantFinder",
            "0002_category_connection_requesttype_user_phone_message_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default=0, max_length=128, region=None
            ),
            preserve_default=False,
        ),
    ]
