# Generated by Django 5.0.4 on 2024-05-04 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistantFinder", "0004_notification_read"),
    ]

    operations = [
        migrations.RenameField(
            model_name="connection",
            old_name="date",
            new_name="datetime",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="date",
            new_name="timestamp",
        ),
        migrations.RenameField(
            model_name="request",
            old_name="date",
            new_name="datetime",
        ),
        migrations.RemoveField(
            model_name="message",
            name="byInstructor",
        ),
        migrations.RemoveField(
            model_name="message",
            name="connection",
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "mentor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mentor_chatrooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_chatrooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="connection",
            name="chatRoom",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                to="assistantFinder.chatroom",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="chatroom",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="assistantFinder.chatroom",
            ),
            preserve_default=False,
        ),
    ]
