# Generated by Django 4.2.11 on 2024-06-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_user_image_profileimagea'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profileimagea',
            new_name='Profileimage',
        ),
    ]
