# Generated by Django 4.2.11 on 2024-06-17 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_profileimage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='title',
        ),
    ]
