# Generated by Django 4.2.11 on 2024-06-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_profileimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='image/user.png', upload_to='image/'),
        ),
        migrations.DeleteModel(
            name='Profileimage',
        ),
    ]
