# Generated by Django 4.2.11 on 2024-06-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_image_delete_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='image/user.png', null=True, upload_to='image/'),
        ),
    ]
